/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package image_details;

import java.io.IOException;

public class Main {
    public static void main(String[] args) {
        Filer f = new Filer();
        try {
            f.loadFile("./test.txt");
        } catch (IOException io) {
            System.out.println(io.getMessage());
        }
    }
}
