/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fi.laresi.image_details;


public class Main {

    public static void main(String[] args) {
        PNGDecoder dec = new PNGDecoder();
        try {
            dec.loadFile(args[0]);
            dec.readChunks();
        } catch (ArrayIndexOutOfBoundsException oob) {
            System.out.println("Program requires that atleast one filepath as an argument to be given");
            System.exit(1);
        } catch (IllegalArgumentException iae) {
            System.out.println("Given file wasn't an PNG image");
            System.exit(1);
        }
    }
}
